### ISSUE TITLE
easy solution

### ISSUE THREAD

**Issue by anuragsingk** [thibautsabot/bypass-license-verification#4]
You can eaisly decode any script /plugin using licensebox as validation for purchase just return reponse value and you're done 3 line of code only 😛

**Comment by tanercanbilgin** [comment]
can you show me an example, thanks

**Comment by anuragsingk** [comment]
Eg : 
$response['status'] = true;
	$response['lic_response']= 'ghostrrr';

**Comment by tanercanbilgin** [comment]
can you send me full code of an example

**Comment by Dondorobuchi** [comment]
WERE YOU ABLE TO GET IT WORKING, PLEASE SHARE
